version: "3.8"
services:
  redis:
    image: redis:6.2.1-alpine
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "6379:6379"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8.023
    volumes:
      - /etc/localtime:/etc/localtime
    command: --default-authentication-plugin=mysql_native_password  
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

