version: "3.8"
services:
  
  nginx:
    volumes:
      - /opt/ops/poppy-devops/poppy/dev/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
  poppy-server:
    image:
    volumes:
      - /opt/ops/poppy-devops/poppy/dev/popp-server:/app/node_modules/@x-poppy/poppy-server/dist/config
    environment:
      - NODE_ENV=production
  ports:
    - mode: host
      protocol: tcp
      published: 80
      target: 80
    - mode: host
      protocol: tcp
      published: 443
      target: 443

  redis:
    image: redis:6.2.1-alpine
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "6379:6379"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8
    volumes:
      - /etc/localtime:/etc/localtime
    command: --default-authentication-plugin=mysql_native_password  
    ports:
      - "3306:3306"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example

