version: "3.8"
services:
  poppy-server:
    image: docker.pkg.github.com/x-poppy/poppy-server/poppy-server:0.0.8
    volumes:
      - /opt/ops/poppy-devops/poppy/dev/popp-server:/app/node_modules/@x-poppy/poppy-server/dist/config
    environment:
      - NODE_ENV=production
      - /etc/localtime:/etc/localtime
  ports:
    - "7001:7001"
  deploy:
    mode: replicated  
    replicas: 2
    restart_policy:
      condition: on-failure  

  redis:
    image: redis:6.2.1-alpine
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - "6379:6379"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8
    volumes:
      - /etc/localtime:/etc/localtime
    command: --default-authentication-plugin=mysql_native_password  
    ports:
      - "3306:3306"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: example

